### ISSUE TITLE
Support libraw options

### ISSUE THREAD

**Issue by campaul** [photoshell/rawkit#6]

**Comment by SamWhited** [comment]
## Phase 1

### Dcraw reconstruction options

- [ ] `deadpixels` *str* -- Filename to read bad pixels from insetad of `.badpixels`.
- [ ] `darkframe` *str* -- Filename to read a darkframe from.
- [ ] `darkness` *int* -- Darkness level.
- [ ] `saturation` *int* -- Saturation.
- [ ] `noise_threshold` *int* -- Wavelet noise reduction (generally ~100–1000).
- [ ] `color_correction` *tuple* `(red_mag float, blue_mag float)` -- Scale the red and blue layers to fix chromatic aberration (defaults to `(0.999, 1.001)`).
- [ ] `highlights` *int* -- Clip or blend highlights.
  - `CLIP = 0` = 0 (default)  -- Clip all highlights to white.
  - `IGNORE = 1` -- Leave highlights unclipped in various shades of pink.
  - `BLEND = 2` -- Blend clipped and unclipped values for a gradual fade to white.
  - 3+ -- Reconstruct highlights with various levels of aggressiveness.
  - `RECONSTRUCT = 5` -- A good compromise.

### Dcraw color options

  - [ ] `white_balance` (*Enum*, or *tuple*)
    - `CAMERA` (default) -- Use the camera's white balance if specified. Otherwise fallback to...
    - `AVERAGE` -- Calculate the white balance by averaging the entire image.
    - `AREA` -- Calculate based on a neutral area (expects a `(left, top, width, height)` iterable).
    - `CUSTOM` -- Also expect an array of 4 multipliers.
    - Need to decide on an API for setting custom/area WB. A WB class, or a setter method, or a second option for each?
  - [ ] `color_space` (*Enum*) -- Select the output color space.
    - `RAW = 0`
    - `SRGB = 1` (default)
    - `ADOBE = 2`
    - `WIDE_GAMUT = 3`
    - `KODAK = 4`
    - `XYZ = 5`

## Phase 2

  - [ ] Use color matrix from camera metadata (see `man dcraw` under Color Options)
  - `profile` *string* or const *EMBEDDED* -- Use the ICC color profile from a file or the embedded one (See #26)

### Libraw only / rawkit only options

  - TODO: Add libraw things or anything we want to do ourselves here.

**Comment by campaul** [comment]
We can handle white balance like this with class methods and a WhiteBalance object.

from rawkit.color import WhiteBalance

```python
{
	'white_balamce': WhiteBalance.camera
}

{
	'white_balamce': WhiteBalance.greybox(,,,)
}

{
	'white_balamce': WhiteBalance.auto
}

{
	'white_balamce': WhiteBalance.manual(,,,)
}
```

**Comment by campaul** [comment]
We also need to support setting the bit depth of output. It can only ever be 8 or 16, so it can probably just be a constant.

**Comment by SamWhited** [comment]
What happens if we just construct a `WhiteBalance` object, eg:

```python
{
  'white_balance': WhiteBalance()
}
```

It seems reasonable to me that that should be the same as `.camera` by default, or possibly also be able to take init arguments to make it a manual one. Or we could just throw a `TypeError` or something.

**Comment by SamWhited** [comment]
We may also want to normalize some of these options; they're all different scales and units which aren't documented anywhere that I can find (I'm having to set things by a mix of educated guessing and trial and error to test the options as I add them).

**Comment by SamWhited** [comment]
Unexpected problem with the current approach to options which I should have thought of: It's hard to document them w/o adding a bunch of verbose placeholder methods (which I suppose is fine as we'll be doing that for a lot of options to normalize or validate them anyways).

Also, I sort of miss being able to set options with a literal (eg. `options = { 'some': 'stuff', 'some_other': 'stuff' }`) like you got with a dict.
